title: Saumya Sahai
redirect_to: "https://sahaisaumya.github.io/"
url: "https://sahaisaumya.github.io/"
baseurl: ""

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass
    
tracking_id: UA-179107942-1

nav:
 - name: "About"
   link: ""
 - name: "CV"
   link: "cv"
 - name: "Contact"
   link: "contact"
