title: Saumya Sahai
url: "https://sahaisaumya.github.io"
baseurl: "/about"

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
