title: Saumya Sahai
authors: Saumya Sahai
url: "https://sahaisaumya.github.io/"
baseurl: "index"

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass
    
tracking_id: UA-179107942-1

nav:
 - name: "CV"
   link: "cv"
 - name: "Code"
   link: "https://github.com/sahaisaumya"
 - name: "Contact"
   link: "contact"
