title: Saumya Y Sahai
authors: Saumya Y Sahai
url: "https://sahaisaumya.github.io"
baseurl: ""

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass
    
tracking_id: G-6TLNMTT8FB

nav:
 - name: "About"
   link: "index"
 - name: "CV"
   link: "cv"
#  - name: "Code"
#    link: "https://github.com/sahaisaumya"
 - name: "Contact"
   link: "contact"
